<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\Imagens\calculator_icon_150972.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Imagens\calculator_icon_150972.ico" />
  </ItemGroup>

</Project>